# Generated by Django 5.0.6 on 2024-06-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingMode',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('operating_mode', models.CharField(max_length=50)),
            ],
        ),
    ]
