# Generated by Django 5.0.6 on 2024-06-08 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_calendar', '0002_operatingmode'),
        ('users', '0005_userprofile_operating_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('calendar_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_calendar.calendarday')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'unique_together': {('doctor', 'calendar_day')},
            },
        ),
    ]
