# Generated by Django 5.0.6 on 2024-06-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_schedule', '0002_doctorschedule_end_time_doctorschedule_lunch_break'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='end_time',
            field=models.TimeField(),
        ),
    ]
