# Generated by Django 5.0.6 on 2024-06-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wage_rate',
            field=models.DecimalField(choices=[(0.25, '0.25'), (0.5, '0.5'), (0.75, '0.75'), (1.0, '1.0'), (1.25, '1.25')], decimal_places=2, default=1, max_digits=3),
        ),
    ]
