# Generated by Django 5.0.6 on 2024-06-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='code',
            field=models.CharField(default='5.1.86.', max_length=20),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
    ]
