# Generated by Django 5.0.6 on 2024-06-08 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_calendar', '0002_operatingmode'),
        ('users', '0004_remove_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='operating_mode',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='production_calendar.operatingmode'),
            preserve_default=False,
        ),
    ]
