# Generated by Django 5.0.6 on 2024-06-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_userprofile_operating_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
