# Generated by Django 5.0.6 on 2024-06-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_userprofilemodality_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="wage_rate",
            field=models.FloatField(
                choices=[
                    (0.25, "0.25"),
                    (0.5, "0.5"),
                    (0.75, "0.75"),
                    (1.0, "1.0"),
                    (1.25, "1.25"),
                ],
                default=1,
            ),
        ),
    ]
