# Generated by Django 5.0.6 on 2024-06-07 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_examination', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modality',
            name='modality_specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.specialization'),
        ),
        migrations.AddField(
            model_name='medicalexamination',
            name='examination_modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_examination.modality'),
        ),
    ]
