# Generated by Django 5.0.6 on 2024-06-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_examination', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modality',
            name='modality_specialization',
        ),
    ]
